#version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    cap_add:
      - NET_RAW
    volumes:
      - ./keys/netsnap_id_rsa:/code/ansible/id_rsa_netsnap:ro    
    networks:
      - demo-net

  # PC Simulado 1
  pc1:
    build: ./pc-ssh
    container_name: pc1
    environment:
      - SSH_USERNAME=admin
      - SSH_PASSWORD=adminpass
    ports:
      - "2222:22"
    volumes:
      - ./keys/netsnap_id_rsa.pub:/authorized_keys:ro
    networks:
      - demo-net


  # PC Simulado 2
  pc2:
    image: alpine
    command: ["sleep", "infinity"]
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
