#version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    cap_add:
      - NET_RAW
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=netsnap
      - DB_USER=admin
      - DB_PASSWORD=adminpass
    networks:
      - demo-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: netsnap
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - demo-net

  # PC Simulado 1
  pc1:
    build: ./pc-ssh
    container_name: pc1
    environment:
      - SSH_USERNAME=admin
      - SSH_PASSWORD=adminpass
    ports:
      - "2222:22"
    networks:
      - demo-net


  # PC Simulado 2
  pc2:
    image: alpine
    container_name: pc2
    command: ["sleep", "infinity"]
    networks:
      - demo-net

  # PC Simulado 3
  pc3:
    build: ./pc-ssh
    container_name: pc3
    environment:
      - SSH_USERNAME=admin
      - SSH_PASSWORD=adminpass
    ports:
      - "2223:22"
    networks:
      - demo-net

  # PC Simulado 4
  pc4:
    image: alpine
    container_name: pc4
    command: ["sleep", "infinity"]
    networks:
      - demo-net

  # PC Simulado 5
  pc5:
    build: ./pc-ssh
    container_name: pc5
    environment:
      - SSH_USERNAME=admin
      - SSH_PASSWORD=adminpass
    ports:
      - "2224:22"
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge

volumes:
  postgres_data: