---
- name: Recolectar información y agrupar resultados
  hosts: servidores
  gather_facts: true
  tasks:
    - name: Registrar información de cada máquina
      set_fact:
        host_info:
          host: "{{ inventory_hostname }}"
          ip: "{{ ansible_default_ipv4.address }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          cpu_cores: "{{ ansible_processor_cores }}"
          cpu_model: "{{ ansible_processor[1] }}"
          ram_mb: "{{ ansible_memtotal_mb }}"
          disk_root_gb: "{{ ansible_mounts[0].size_total // (1024 * 1024 * 1024) }}"
          uptime_hours: "{{ ansible_uptime_seconds | int // 3600 }}"
      register: info_result

    - name: Añadir info de esta máquina al grupo "resultados"
      add_host:
        name: "localhost"
        groups: resultados
        host_info: "{{ host_info }}"

- name: Consolidar resultados
  hosts: resultados
  gather_facts: false
  tasks:
    - name: Mostrar información agrupada de todas las máquinas
      debug:
        var: hostvars[inventory_hostname]['host_info']
